import os
import math
import torch
import torch.nn as nn
import torchvision.transforms as transforms
from tqdm import tqdm
from PIL import Image
import json

# -------------------------------
# Define the simplified conditional UNet and helper functions
# -------------------------------

class SinusoidalTimeEmbedding(nn.Module):
    def __init__(self, dim):
        super().__init__()
        self.dim = dim

    def forward(self, t):
        half_dim = self.dim // 2
        emb = math.log(10000) / (half_dim - 1)
        emb = torch.exp(torch.arange(half_dim, device=t.device) * -emb)
        emb = t.float().unsqueeze(1) * emb.unsqueeze(0)
        emb = torch.cat([torch.sin(emb), torch.cos(emb)], dim=1)
        if self.dim % 2 == 1:  # zero pad if needed
            emb = torch.cat([emb, torch.zeros(t.size(0), 1, device=t.device)], dim=1)
        return emb

class ConditionalUNet(nn.Module):
    def __init__(self, time_emb_dim=128, text_emb_dim=512):
        super().__init__()
        self.time_mlp = nn.Sequential(
            SinusoidalTimeEmbedding(time_emb_dim),
            nn.Linear(time_emb_dim, time_emb_dim),
            nn.ReLU()
        )
        self.down = nn.Sequential(
            nn.Conv2d(3, 64, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.Conv2d(64, 128, kernel_size=4, stride=2, padding=1),  # from 256 -> 128
            nn.ReLU(),
        )
        self.bottleneck = nn.Sequential(
            nn.Conv2d(128, 128, kernel_size=3, padding=1),
            nn.ReLU(),
        )
        self.condition_proj = nn.Linear(time_emb_dim + text_emb_dim, 128)
        self.up = nn.Sequential(
            nn.ConvTranspose2d(128, 64, kernel_size=4, stride=2, padding=1),  # from 128 -> 256
            nn.ReLU(),
            nn.Conv2d(64, 3, kernel_size=3, padding=1)
        )

    def forward(self, x, t, text_embedding):
        t_emb = self.time_mlp(t)  # (B, time_emb_dim)
        cond = torch.cat([t_emb, text_embedding], dim=1)  # (B, time_emb_dim + text_emb_dim)
        cond = self.condition_proj(cond)  # (B, 128)
        cond = cond.unsqueeze(-1).unsqueeze(-1)  # (B, 128, 1, 1)
        x_down = self.down(x)         # (B, 128, H/2, W/2)
        x_bot = self.bottleneck(x_down)
        x_bot = x_bot + cond
        out = self.up(x_bot)
        return out

# -------------------------------
# Diffusion Schedule Helpers
# -------------------------------
T = 1000  # total diffusion steps

def linear_beta_schedule(timesteps):
    beta_start = 0.0001
    beta_end = 0.02
    return torch.linspace(beta_start, beta_end, timesteps)

betas = linear_beta_schedule(T)
alphas = 1.0 - betas
alphas_cumprod = torch.cumprod(alphas, dim=0)

def extract(a, t, x_shape):
    batch_size = t.shape[0]
    out = a.gather(-1, t.cpu()).reshape(batch_size, *((1,) * (len(x_shape) - 1))).to(t.device)
    return out

# -------------------------------
# GLIDE Model Inference Function
# -------------------------------
# This function loads the saved model and uses it to generate an image from a caption.
# (For simplicity, here we assume the text embedding is generated by a dummy process.)
# In your real implementation, you would replace this with your actual text embedding process.
def get_dummy_text_embedding(text, device):
    # Replace this with your actual CLIP or other text encoder inference
    # Here we simply return a zero tensor (of shape [1, 512])
    return torch.zeros(1, 512, device=device)

def generate_image_from_caption(input_caption, model_path, device="cpu"):
    # Load the model
    model = ConditionalUNet().to(device)
    model.load_state_dict(torch.load(model_path, map_location=device))
    model.eval()

    # Obtain text embedding (here we use a dummy embedding; replace with your own)
    text_embedding = get_dummy_text_embedding(input_caption, device)

    # Start from pure noise
    img_size = 256
    current_image = torch.randn(1, 3, img_size, img_size, device=device)

    # Reverse diffusion process (a simplified deterministic version)
    for i in tqdm(reversed(range(T)), desc="Generating Image"):
        t = torch.full((1,), i, device=device, dtype=torch.long)
        with torch.no_grad():
            predicted_noise = model(current_image, t, text_embedding)
        a_t = extract(alphas_cumprod, t, current_image.shape)
        beta_t = extract(betas, t, current_image.shape)
        current_image = (current_image - (beta_t / torch.sqrt(1 - a_t)) * predicted_noise) / torch.sqrt(1 - beta_t)

    # Denormalize: from [-1, 1] to [0, 1]
    generated_image = current_image.squeeze(0).cpu().detach()
    generated_image = (generated_image * 0.5 + 0.5).clamp(0, 1)
    pil_img = transforms.ToPILImage()(generated_image)
    return pil_img

# If you want, you can add a main block for testing:
if __name__ == "__main__":
    caption = input("Enter a caption for image generation: ")
    output_img = generate_image_from_caption(caption, os.path.join(os.path.dirname(__file__), "glide_diffusion_model.pth"), device="cpu")
    output_img.show()
